#!/usr/bin/env python3
"""
generate_codex_agents.py
------------------------
Automatically generates AGENTS.md files for Codex by aggregating 
Antigravity's workspace rules (.agent/rules/GEMINI.md) and 
specialist instructions (.agent/agents/).
"""

import os

def generate_agents():
    # Setup paths relative to script location
    script_dir = os.path.dirname(os.path.abspath(__file__))
    root_dir = os.path.abspath(os.path.join(script_dir, "..", ".."))
    agent_dir = os.path.join(root_dir, ".agent")
    rules_dir = os.path.join(agent_dir, "rules")
    agents_dir = os.path.join(agent_dir, "agents")

    print("🚀 Starting Codex AGENTS.md Generation...")

    # 1. Generate Root AGENTS.md (Global Workspace Rules)
    gemini_path = os.path.join(rules_dir, "GEMINI.md")
    root_agents_path = os.path.join(root_dir, "AGENTS.md")

    root_header = (
        "# AGENTS.md (Workspace Rules)\n\n"
        "> 🤖 **Note**: This file is automatically generated from `.agent/rules/GEMINI.md` "
        "to ensure Codex follows workspace guidelines. **Do not edit manually.**\n\n"
        "---\n\n"
    )

    if os.path.exists(gemini_path):
        with open(gemini_path, 'r', encoding='utf-8') as f:
            content = f.read()
        with open(root_agents_path, 'w', encoding='utf-8') as f:
            f.write(root_header + content)
        print(f"✅ Generated root-level AGENTS.md from GEMINI.md")
    else:
        print(f"⚠️ Warning: Rules file {gemini_path} not found.")

    # 2. Generate Specialist Overrides for Subdirectories
    # Maps workspace subdirectories to specialist agent files in .agent/agents/
    mappings = {
        "backend": "backend-specialist.md",
        "frontend": "frontend-specialist.md",
        "docs": "documentation-writer.md",
        "scripts": "devops-engineer.md"
    }

    for dir_name, agent_file in mappings.items():
        target_dir = os.path.join(root_dir, dir_name)
        
        # Only create override if the subdirectory exists
        if os.path.exists(target_dir) and os.path.isdir(target_dir):
            agent_path = os.path.join(agents_dir, agent_file)
            
            if os.path.exists(agent_path):
                target_agents_path = os.path.join(target_dir, "AGENTS.md")
                
                header_override = (
                    f"# AGENTS.md ({dir_name.capitalize()} Specialist Override)\n\n"
                    f"> 🤖 **Note**: This file is automatically generated from `.agent/agents/{agent_file}` "
                    f"to ensure Codex assumes the specialized role for this directory. "
                    f"**Do not edit manually.**\n\n"
                    "---\n\n"
                )
                
                with open(agent_path, 'r', encoding='utf-8') as f:
                    content = f.read()
                with open(target_agents_path, 'w', encoding='utf-8') as f:
                    f.write(header_override + content)
                print(f"✅ Generated specialist override for {dir_name}/AGENTS.md")
            else:
                print(f"💡 Info: Specialist file {agent_file} not found for {dir_name}, skipping.")
        else:
            # print(f"💡 Info: Subdirectory {dir_name} not found in root, skipping.")
            pass

    print("🎉 Codex AGENTS.md sync complete!")

if __name__ == "__main__":
    generate_agents()
